In [41]:
l = [0, 1, 2, 3, 4, 5, 6]

In [42]:
l2 = ['A, B, C, D, F, G']

# .append

In [43]:
l.append(l2)

In [44]:
l

[0, 1, 2, 3, 4, 5, 6, ['A, B, C, D, F, G']]

# .extend

In [45]:
l.extend(l2)

In [46]:
l

[0, 1, 2, 3, 4, 5, 6, ['A, B, C, D, F, G'], 'A, B, C, D, F, G']

# .insert

In [32]:
l.insert(3, "lalala")

In [33]:
l

[0, 1, 2, 'lalala', 3, 4, 5, 6, ['A, B, C, D, F, G'], 'A, B, C, D, F, G']

# del[]

In [35]:
del l[3]

In [36]:
l

[0, 1, 2, 3, 4, 5, 6, ['A, B, C, D, F, G'], 'A, B, C, D, F, G']

In [37]:
del l[7]

In [38]:
l

[0, 1, 2, 3, 4, 5, 6, 'A, B, C, D, F, G']

In [39]:
del l[7]

In [40]:
l

[0, 1, 2, 3, 4, 5, 6]

# .remove()

In [47]:
l

[0, 1, 2, 3, 4, 5, 6, ['A, B, C, D, F, G'], 'A, B, C, D, F, G']

In [50]:
l.remove('A, B, C, D, F, G')

In [51]:
l

[0, 1, 2, 3, 4, 5, 6, ['A, B, C, D, F, G']]

In [52]:
l.remove(['A, B, C, D, F, G'])

In [53]:
l

[0, 1, 2, 3, 4, 5, 6]

In [54]:
l.remove(0)

In [55]:
l

[1, 2, 3, 4, 5, 6]

In [56]:
l2 = ['A, B, C, D, F, G']

In [57]:
l + l2

[1, 2, 3, 4, 5, 6, 'A, B, C, D, F, G']

# .count() -подсчёт значений в списке

In [69]:
l = l + l2

In [70]:
l

[1, 2, 3, 4, 5, 6, 'A, B, C, D, F, G', 'A, B, C, D, F, G']

In [63]:
l.count(1)

1

In [65]:
l.count('A')

0

In [66]:
l.count('A, B, C, D, F, G')

1

In [71]:
l[6]

'A, B, C, D, F, G'

In [72]:
l[5]

6

In [73]:
l[-1]

'A, B, C, D, F, G'

# numpy.random.randn() в Python

In [1]:
import numpy as np

In [2]:
data = {i : np.random.randn() for i in range(7)}
data

{0: -0.6734940875943568,
 1: -0.1659472802539324,
 2: -2.9109678775679257,
 3: -0.3693821392469588,
 4: 1.4556705409832011,
 5: 1.0860794395516031,
 6: 1.07704975374296}

In [ ]:
# numpy.random.randn() создает массив указанных фигур и заполняет их 
#     случайными заданными значениями в соответствии со стандартным гауссовым 
#     или нормальным распределением.
# np.random.randn() — это метод библиотеки numpy, 
#        который возвращает образец (или образцы) из «стандартного нормального»
#        распределения в Python. 
#        Он принимает размеры возвращаемого массива в качестве аргумента 
#         и возвращает либо ndarray, либо, если аргумент не указан, 
#         возвращает значение с плавающей запятой.
# np.random.randn() возвращает все значения в форме с плавающей запятой 
#                         и в среднем распределении = 0 и дисперсии = 1.

In [3]:
## app.py
data = np.random.randn()
print(data)

0.026538972439196732


In [4]:
data = np.random.randn(6)
data

array([ 1.01873851,  0.74864456, -1.17699749,  0.2281168 , -0.38242588,
       -0.80155777])

In [9]:
data = np.random.randn(10)
data

array([-0.00869795,  0.42186511, -0.71018743, -1.06889905, -1.13776303,
        0.87378921,  0.13805272, -0.75606467,  1.79075616, -0.00805362])

In [10]:
data = np.random.randn(2, 2)
data

array([[-1.54678632, -0.29016622],
       [-0.0047577 , -1.82727464]])

In [13]:
data = np.random.randn(3, 3)
data

array([[-0.10449037,  0.41099028,  0.58409525],
       [-1.22374282,  1.46778048, -0.25587264],
       [-0.68898966, -0.07829202, -0.71188323]])

In [14]:
data = np.random.randn(3, 5)
data

array([[ 1.25829587,  1.18284624, -0.42278809, -0.15226566,  0.52039258],
       [ 0.86010939,  1.09227163, -0.14044717, -1.07600682,  1.045813  ],
       [ 1.96009433, -1.66221448,  0.56526254, -1.01034622,  1.13170489]])

In [15]:
data = np.random.randn(10, 5)
data

array([[-0.68694546, -1.59339659,  0.80010312,  0.66362357, -0.30160463],
       [ 1.54246202,  0.7753288 , -0.24511617, -1.55750728, -0.93509076],
       [-0.12327255, -0.45701984, -0.66333103, -0.0386543 , -0.15175604],
       [-0.47639024,  1.1995223 , -0.41118668, -0.01247181, -0.58369471],
       [-0.15843884,  0.14250558,  0.65632541,  0.54410209, -0.47489883],
       [-0.44172986,  0.7095074 , -0.04636617, -1.02585685, -0.80541663],
       [-0.53357352,  0.0126668 , -0.05988623,  0.75341518,  0.13772142],
       [-0.91127121,  0.90376836,  0.28835853, -0.02650781, -0.36936718],
       [ 1.30079716,  0.7652266 ,  1.00173959, -0.053994  ,  0.02734477],
       [-0.3625833 , -0.86723493, -0.11780395, -1.31923124,  0.71226736]])

In [18]:
data = np.random.randn(3, 3, 3)
data

array([[[-1.5971511 , -0.97562231,  0.42257936],
        [-0.1309545 , -0.16178452,  1.11482877],
        [-0.00503759,  0.76104452, -0.56257499]],

       [[-0.55781793,  1.17344264, -1.58235546],
        [ 0.25030318,  1.31654919,  0.44442252],
        [-1.14544969, -0.86290735, -0.73804847]],

       [[-2.40626033, -1.00248622,  1.11826352],
        [-1.47229565,  1.02990596,  0.01156015],
        [-1.44260361,  1.37747784,  0.45999827]]])

In [24]:
class Cat:
    def __init__(self, name, age):
        self.name = name
        self.age = age
 
    def __str__(self):
        return f'Cat(name={self.name}, age={self.age})'

In [25]:
class Cat:
    def __init__(self, name, age):
        self.name = name
        self.age = age
 
    def __str__(self):
        return f'Cat(name={self.name}, age={self.age})'
 
    def __repr__(self):
        return f'Cat(name={self.name!r}, age={self.age!r})'